defmodule BeamDcd.EntrypointDetector do
  @moduledoc """
  Identifies and filters compiler-generated functions, OTP behaviour callbacks,
  and framework-specific entrypoints that should not be reported as unused.
  """

  @type mfa_tuple :: {module(), atom(), arity()}

  # Functions generated by the compiler that are always present
  @compiler_generated_fa [
    {:module_info, 0},
    {:module_info, 1},
    {:__info__, 1},
    {:behaviour_info, 1},
    {:__impl__, 1},
    {:__struct__, 0},
    {:__struct__, 1},
    {:__changeset__, 0}
  ]

  # Known OTP and framework behaviour callbacks
  @otp_behaviour_callbacks %{
    :gen_server => [
      {:init, 1}, {:handle_call, 3}, {:handle_cast, 2}, {:handle_info, 2},
      {:terminate, 2}, {:code_change, 3}, {:format_status, 1}, {:format_status, 2}
    ],
    :gen_statem => [
      {:init, 1}, {:callback_mode, 0}, {:terminate, 3}, {:code_change, 4},
      {:format_status, 1}, {:format_status, 2}
    ],
    :gen_event => [
      {:init, 1}, {:handle_event, 2}, {:handle_call, 2}, {:handle_info, 2},
      {:terminate, 2}, {:code_change, 3}, {:format_status, 2}
    ],
    :supervisor => [{:init, 1}],
    :application => [{:start, 2}, {:stop, 1}, {:prep_stop, 1}, {:config_change, 3}],
    GenServer => [
      {:init, 1}, {:handle_call, 3}, {:handle_cast, 2}, {:handle_info, 2},
      {:terminate, 2}, {:code_change, 3}, {:format_status, 1}, {:format_status, 2},
      {:handle_continue, 2}
    ],
    Supervisor => [{:init, 1}],
    Application => [{:start, 2}, {:stop, 1}, {:prep_stop, 1}, {:config_change, 3}],
    Phoenix.LiveView => [
      {:mount, 3}, {:render, 1}, {:handle_event, 3}, {:handle_params, 3},
      {:handle_info, 2}, {:handle_async, 3}
    ],
    Phoenix.LiveComponent => [
      {:mount, 1}, {:update, 2}, {:render, 1}, {:handle_event, 3},
      {:preload, 1}, {:update_many, 1}
    ],
    Phoenix.Channel => [
      {:join, 3}, {:handle_in, 3}, {:handle_info, 2}, {:handle_out, 3},
      {:terminate, 2}
    ],
    Plug => [{:init, 1}, {:call, 2}],
    Ecto.Migration => [{:up, 0}, {:down, 0}, {:change, 0}],
    Mix.Task => [{:run, 1}]
  }

  @spec compiler_generated?(mfa_tuple()) :: boolean()
  def compiler_generated?({_module, function, arity}) do
    {function, arity} in @compiler_generated_fa or
      String.starts_with?(to_string(function), "MACRO-")
  end

  @spec detect_behaviours(keyword()) :: [module()]
  def detect_behaviours(attributes) do
    behaviours =
      Keyword.get_values(attributes, :behaviour) ++
        Keyword.get_values(attributes, :behavior)

    List.flatten(behaviours)
  end

  @spec get_behaviour_callbacks([module()]) :: [{atom(), arity()}]
  def get_behaviour_callbacks(behaviours) do
    behaviours
    |> Enum.flat_map(fn behaviour ->
      case Map.get(@otp_behaviour_callbacks, behaviour) do
        nil -> try_load_behaviour_callbacks(behaviour)
        callbacks -> callbacks
      end
    end)
    |> Enum.uniq()
  end

  @spec is_entrypoint?(mfa_tuple(), keyword(), [mfa_tuple()]) :: boolean()
  def is_entrypoint?({_mod, fun, arity} = mfa, attributes, extra_entrypoints) do
    compiler_generated?(mfa) or
      is_on_load?(fun, arity, attributes) or
      is_behaviour_callback?(fun, arity, attributes) or
      mfa in extra_entrypoints
  end

  @spec filter_entrypoints([mfa_tuple()], keyword(), [mfa_tuple()]) :: [mfa_tuple()]
  def filter_entrypoints(exports, attributes, extra_entrypoints \\ []) do
    Enum.reject(exports, &is_entrypoint?(&1, attributes, extra_entrypoints))
  end

  defp is_on_load?(function, arity, attributes) do
    on_load = Keyword.get(attributes, :on_load, [])

    case on_load do
      {f, a} -> f == function and a == arity
      [{f, a}] -> f == function and a == arity
      _ -> false
    end
  end

  defp is_behaviour_callback?(function, arity, attributes) do
    behaviours = detect_behaviours(attributes)
    callbacks = get_behaviour_callbacks(behaviours)
    {function, arity} in callbacks
  end

  defp try_load_behaviour_callbacks(behaviour) do
    if Code.ensure_loaded?(behaviour) and function_exported?(behaviour, :behaviour_info, 1) do
      try do
        behaviour.behaviour_info(:callbacks)
      rescue
        _ -> []
      end
    else
      []
    end
  end
end
